Work around FileNotFoundError if rss/ doesn't exist yet
  Traceback (most recent call last):
    File "./postprocessing.py", line 44, in <module>
      fg.rss_file('rss/' + user + '.xml') # Write the RSS feed to a file
    File "/home/runner/.local/lib/python3.8/site-packages/feedgen/feed.py", line 416, in rss_file
      doc.write(filename, pretty_print=pretty, encoding=encoding,
    File "src/lxml/etree.pyx", line 2057, in lxml.etree._ElementTree.write
    File "src/lxml/serializer.pxi", line 746, in lxml.etree._tofilelike
    File "src/lxml/serializer.pxi", line 813, in lxml.etree._create_output_buffer
    File "src/lxml/serializer.pxi", line 803, in lxml.etree._create_output_buffer
  FileNotFoundError: [Errno 2] No such file or directory